
#define TestCaseCount 6

#define TestCase1 \
{"??",\
 "??"}

#define TestCase2 \
{"B?",\
 "??"}

#define TestCase3 \
{"WWB",\
 "WWW",\
 "WWW",\
 "WWW"}

#define TestCase4 \
{"BBBBBB",\
 "WWBBBB",\
 "WBBBBB"}

#define TestCase5 \
{"?BB?",\
 "BBBB",\
 "?BB?"}

#define TestCase6 \
{"?WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",\
 "B?WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",\
 "BB?WWWWWWWWWWWWWWWWWWWWWWWWWWWW",\
 "BBB?WWWWWWWWWWWWWWWWWWWWWWWWWWW",\
 "BBBB?WWWWWWWWWWWWWWWWWWWWWWWWWW",\
 "BBBBB?WWWWWWWWWWWWWWWWWWWWWWWWW",\
 "BBBBBB?WWWWWWWWWWWWWWWWWWWWWWWW",\
 "BBBBBBB?WWWWWWWWWWWWWWWWWWWWWWW",\
 "BBBBBBBB?WWWWWWWWWWWWWWWWWWWWWW",\
 "BBBBBBBBB?WWWWWWWWWWWWWWWWWWWWW",\
 "BBBBBBBBBB?WWWWWWWWWWWWWWWWWWWW",\
 "BBBBBBBBBBB?WWWWWWWWWWWWWWWWWWW",\
 "BBBBBBBBBBBB?WWWWWWWWWWWWWWWWWW",\
 "BBBBBBBBBBBBB?WWWWWWWWWWWWWWWWW",\
 "BBBBBBBBBBBBBB?WWWWWWWWWWWWWWWW",\
 "BBBBBBBBBBBBBBB?WWWWWWWWWWWWWWW",\
 "BBBBBBBBBBBBBBBB?WWWWWWWWWWWWWW",\
 "BBBBBBBBBBBBBBBBB?WWWWWWWWWWWWW",\
 "BBBBBBBBBBBBBBBBBB?WWWWWWWWWWWW",\
 "BBBBBBBBBBBBBBBBBBB?WWWWWWWWWWW",\
 "BBBBBBBBBBBBBBBBBBBB?WWWWWWWWWW",\
 "BBBBBBBBBBBBBBBBBBBBB?WWWWWWWWW",\
 "BBBBBBBBBBBBBBBBBBBBBB?WWWWWWWW",\
 "BBBBBBBBBBBBBBBBBBBBBBB?WWWWWWW",\
 "BBBBBBBBBBBBBBBBBBBBBBBB?WWWWWW",\
 "BBBBBBBBBBBBBBBBBBBBBBBBB?WWWWW",\
 "BBBBBBBBBBBBBBBBBBBBBBBBBB?WWWW",\
 "BBBBBBBBBBBBBBBBBBBBBBBBBBB?WWW",\
 "BBBBBBBBBBBBBBBBBBBBBBBBBBBB?WW",\
 "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB?W"}

#define Answer1 14

#define Answer2 7

#define Answer3 1

#define Answer4 0

#define Answer5 5

#define Answer6 73741817
